### ISSUE TITLE
Doesn't compile some .java files; classes don't see each other

### ISSUE THREAD

**Issue by MEhlinger** [cis2206fall2015/t2p1a#1]
Javac will compile all of the java files as a group with `javac -cp . *.java`, but fails for everything but Employee.java when compiled individually, apparently due to the compiler not seeing the other classes being referenced... appears to be a package name / classpath problem. 

An excerpt from the compiler errors:

``` java
EmployeeDAO.java:21: error: cannot find symbol
    protected final List<Employee> myList;
                         ^
  symbol:   class Employee
  location: class EmployeeDAO
EmployeeDAO.java:40: error: cannot find symbol
    public void createRecord(Employee employee) {
```

I changed the package name to t2p1a, so I thought I might have done this, but trying the same with a fresh clone of the original project (and original package name) produces the same result.

**Comment by MEhlinger** [comment]
Closed - `commit 58e2acd5dafec949cfc0ddf7ad640ad43615d699` "Remove old package name"

Original - and obsolete - old package name was removed, and the bug is gone. If we re-add a package later on, it might have to be reopened-- this is a workaround, and likely temporary, but we should focus on actual functionality before a bug that doesn't seem to affect functionality -- though this is programming by coincidence and we should figure this out one way or another.
